### ISSUE TITLE
Deploying Definition/Composition using Helm conflicts with secret injection for provider

### ISSUE THREAD

**Issue by patpicos** [crossplane-contrib/provider-http#41]
### What problem are you facing?
I deploy my definitions and and compositions using a Helm chart. I also use KCL in my Composition.

When rendering the helm chart to deploy all the compositions/definitions, it errors out because it thinks the secret reference is a sprig function

Excerpt from Composition
```kcl
              headers = {
                "Authorization" = [ 'Bearer {{ bearerToken:crossplane-system:http-provider-config-gitlab }}' ]
                "Content-Type" = ["application/json"]
                "User-Agent" = "Crossplane"
              }
```
Error from Helm Template:
```bash
helm template . --set image.repository=xpkg.upbound.io --set gitlabProvider.enabled=true --set httpProvider.enabled=true | yq  -y '. | select(.kind == "DeploymentRuntimeConfig")' | kubectl apply --context kind-kind -f -
Error: parse error at (crossplane-compositions/templates/apis/XLdapGroup/ldap-kcl-composition.yaml:45): function "bearerToken" not defined

Use --debug flag to render out invalid YAML
error: no objects passed to apply
make: *** [Makefile:18: install-providers] Error 1

```

### How could Crossplane help solve your problem?
Moving credentials to a ProviderConfig like other providers would improve this instead of codifying in the `DisposableRequest.spec.forProvider.headers`

**Comment by arielsepton** [comment]
Hi,

To resolve this error, you can [escape](https://github.com/helm/helm/issues/8236#issuecomment-636927511) the curly braces so that Helm doesn’t try to process them as template syntax.

Here’s how you can modify your Composition to escape the curly braces:

```
headers = {
  "Authorization" = [ 'Bearer {{`{{`} bearerToken:crossplane-system:http-provider-config-gitlab {{`}}`}}' ]
  "Content-Type" = ["application/json"]
  "User-Agent" = "Crossplane"
}
```

While keeping credentials in `ProviderConfig` works for most providers, in this case, each `Request` manages a different resource with unique sensitive data, making it too dynamic. Keeping secrets within each `Request` offers better flexibility and control.

Please give the escaping method a try and let me know if it resolves your issue. If you have any further questions or concerns, feel free to reach out.

**Comment by patpicos** [comment]
That did the trick. your example was missing one closing brace on the left side...but managed to sort it out. I had look at escaping mechanisms...i was doing it wrong.
```
"Authorization" = [ 'Bearer {{`{{`}} bearerToken:crossplane-system:http-provider-config-gitlab {{`}}`}}' ]
```
Thanks for the help. Closing issue
